name: Create Containers

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  IMAGE_NAME_BOT: seraphsix_bot
  IMAGE_NAME_PROXY: seraphsix_oauth_proxy
  IMAGE_NAME_WORKER: seraphsix_arq_worker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
            docker build . --file Dockerfile.oauth_proxy
          fi
 
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Build bot image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME_BOT

      - name: Build oauth proxy image
        run: docker build . --file Dockerfile.oauth_proxy --tag $IMAGE_NAME_PROXY

      - name: Build arq worker image
        run: docker build . --file Dockerfile.arq_worker --tag $IMAGE_NAME_WORKER

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          IMAGE_ID_BOT=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME_BOT
          IMAGE_ID_PROXY=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME_PROXY
          IMAGE_ID_WORKER=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME_WORKER

          # Change all uppercase to lowercase and append version tag
          IMAGE_ID_BOT=$(echo $IMAGE_ID_BOT | tr '[A-Z]' '[a-z]'):${{ steps.tag_version.outputs.new_tag }}
          IMAGE_ID_PROXY=$(echo $IMAGE_ID_PROXY | tr '[A-Z]' '[a-z]'):${{ steps.tag_version.outputs.new_tag }}
          IMAGE_ID_WORKER=$(echo $IMAGE_ID_WORKER | tr '[A-Z]' '[a-z]'):${{ steps.tag_version.outputs.new_tag }}

          echo IMAGE_ID_BOT=$IMAGE_ID_BOT
          echo IMAGE_ID_PROXY=$IMAGE_ID_PROXY
          echo IMAGE_ID_WORKER=$IMAGE_ID_WORKER

          docker tag $IMAGE_NAME_BOT $IMAGE_ID_BOT
          docker push $IMAGE_ID_BOT

          docker tag $IMAGE_NAME_PROXY $IMAGE_ID_PROXY
          docker push $IMAGE_ID_PROXY

          docker tag $IMAGE_NAME_WORKER $IMAGE_ID_WORKER
          docker push $IMAGE_ID_WORKER
